CONFUSION_MATRIX :
[[238   5]
 [ 70 175]]
REPORT :
              precision    recall  f1-score   support
       False       0.77      0.98      0.86       243
        True       0.97      0.71      0.82       245
    accuracy                           0.85       488
   macro avg       0.87      0.85      0.84       488
weighted avg       0.87      0.85      0.84       488
Traceback (most recent call last):
  File "C:\Users\motom\Desktop\Python\Sputnik_voice_autoencoder\main.py", line 47, in <module>
    print("result=", model.predict(test1, test2, "dataset"))
TypeError: Model.predict() takes 3 positional arguments but 4 were given